spring:
  application:
    name: global-solution-api

  # Profile ativo
  profiles:
    active: dev

<<<<<<< HEAD
# Server Configuration
server:
  port: 8080
=======
  # Configuração do Banco H2
  datasource:
    url: jdbc:h2:mem:globalsolutiondb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: gs2
    password: 2025

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # Flyway (Migrations)
  flyway:
    enabled: true
    clean-on-validation-error: true
    clean-disabled: false
    baseline-on-migrate: true
>>>>>>> parent of 9d0c29e (Adicionado testes unitários, criado base secundaria para banco de dados, então dev(principal) -> H2 | prod -> Oracle | e ajustando alguns detalhes extras)

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
    urls:
      - name: Global Solution API
        url: /v3/api-docs

# JWT Configuration
jwt:
  secret: "global-solution-2025-fiap-upskilling-reskilling-secret-key"
  expiration: 3600000  # 1 hora em millisegundos

# Server Configuration
server:
  port: 8080