spring:
  # Oracle Database
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    driverClassName: oracle.jdbc.OracleDriver
    username: RM558540
    password: 160203

  # H2 Console (desabilitado em prod)
  h2:
    console:
      enabled: false

  # JPA/Hibernate (Oracle)
  jpa:
    hibernate:
      ddl-auto: none  # Em produção, NUNCA use update/create
    show-sql: false   # Não exibe SQL em produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: false

  # Flyway (Migrations)
  flyway:
    enabled: true
    clean-on-validation-error: false
    clean-disabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration