spring:
  application:
    name: global-solution-api

  # Profile ativo
  profiles:
    active: dev # dev -> H2 // prod -> oracle

# Server Configuration
server:
  port: 8080

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
    urls:
      - name: Global Solution API
        url: /v3/api-docs